universe:
  stocks:
  # some extra stocks we want to import, but are not in any portfolio
    - SAP.DE
    - RHM.DE
    - HO.PA
    - WM
    - AIR.PA
    - TTE.PA
    - INTU
    - GOOG
    - HEN3.DE
    - BAYN.DE
    - BAS.DE
    - VNA.DE
    - DTE.DE
    - BMW.DE
    - VOW3.DE
    - IBE.MC
    - ORSTED.CO
    - SNOW
    - PLTR
    - CRWD
    - NESN.SW
    - RACE.MI
    - SAP.DE
    - IFX.DE
    - ADYEN.AS
    - SIE.DE
    - INGR
    - DBK.DE
    - ALV.DE
    - JPM
    - HSBA.L
    - GS
    - TSM
    - INTC
    - NOKIA.HE
    - MA
    - MSCI
    - SIE.DE
    - AIR.PA
    - GE
    - UTX
    - HON

  price_only:
    # Currencies & Crypto
    - EURUSD=X
    - EURCHF=X
    - EURGBP=X
    - EURJPY=X
    - EURDKK=X
    - EURSEK=X
    - EURCAD=X

    # ETFs (via Xetra in EUR)
    - EUNL.DE  # iShares Core MSCI World
    - WSRI.PA
    - M7U.DE
    - EUNM.DE  # iShares MSCI EM (Acc)
    - AEME.PA  # Amundi MSCI EM
    - EXSB.DE  # iShares STOXX Europe Small 200
    # For testing purposes: Krypto and Gold
    - BTC-EUR
    - BTC-USD
    - GC=F
    - SI=F

settings:
  base_dir: "data/prod"
  archive_dir: "data/archive"
  initial_price_start_date: "2021-01-01"
